### ISSUE TITLE
Document all the commands and features

### ISSUE THREAD

**Issue by Sid200026** [ToxicBot-Discord/ToxicBot#18]
Update the README.md and add all the commands the bot provides. Use a tabular format with the following columns and add a reference of the commands in the table of contents.

- Command
- Accessible By -> All Users, Bots, Admins etc
- Description

Also refactor README.md ie. it must be soothing to the eye while retaining the same amount of information. If you want, I can give you a list of commands that the bot can perform or else you can go to constants/messages.py and read the HELP and ADMIN_HELP command.

**Comment by fredb1106** [comment]
Can I be assigned to this?

I'd use this project's readme as an inspiration: [https://github.com/httpie/httpie/blob/master/README.rst](https://github.com/httpie/httpie/blob/master/README.rst), if you don't mind ReStructuredText. We could then make a table of commands that would look like this one: [https://github.com/httpie/httpie/blob/master/README.rst#request-items](https://github.com/httpie/httpie/blob/master/README.rst#request-items), get a TOC and heading numbering for free... Restructuring would be much easier

The gif animation is a little more involved though... I was thinking of keeping your YouTube video link but replacing the screenshot/thumbnail.

Let me know

Thanks

**Comment by Sid200026** [comment]
The README in the links provided look very good. I also appreciate the fact that you first gave a brief about how you want to approach this issue. Regarding the youtube thumbnail, you can go ahead and replace it with anything you want.

**Comment by fredb1106** [comment]
Excellent! Thanks for the feedback!

You can expect a PR before the end of the week. If I hit any roadblock I'll let you know

**Comment by Sid200026** [comment]
Sure @fredb1106 . Thanks for the roadmap.
