### ISSUE TITLE
Changing the responses given by the bot

### ISSUE THREAD

**Issue by Sid200026** [ToxicBot-Discord/ToxicBot#19]
Currently the bot responds to the user using normal texts. A more elegant approach would be the usage of discord' Embed. Your task will be to convert each of the responses provided by the bot to a discord Embed.

**Comment by Zebralt** [comment]
Hi, I'd like to work on this.

I guess my plan would be to refactor all `channel.send` calls not yet sending an embed and use a custom function `as_embed(text: str) -> Embed` imported from a helper module to format them consistently.

Just need to decide which embed format to use across all messages as signature.

**Comment by Sid200026** [comment]
The approach sounds good to me. You can go ahead with it.
